crud_mvc_aspnet_core/Controllers/ArticleController.cs
using crud_mvc_aspnet_core.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace crud_mvc_aspnet_core.Controllers
{
    public class ArticleController : BaseController
    {
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Message = "Ingrese los datos del artículo";
            ViewBag.Categories = categoryService.GetCategories();

            return View();
        }

        [HttpPost]
        public IActionResult Create(Article article)
        {
            article.Category = categoryService.GetCategory(article.CategoryId);

            if (ModelState.IsValid)
            {
                articleService.CreateArticle(article);

                TempData["AlertMessage"] = "Se ha agregado el artículo.";
                TempData["AlertStyle"] = AlertConstants.SUCCESS;

                return RedirectToAction("List");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Message = "Datos del artículo";
            ViewBag.Categories = categoryService.GetCategories();

            return View(articleService.GetArticle(id));
        }

        [HttpPost]
        public IActionResult Edit(Article article)
        {
            article.Category = categoryService.GetCategory(article.CategoryId);

            if (ModelState.IsValid)
            {
                articleService.UpdateArticle(article);

                TempData["AlertMessage"] = "Se ha actualizado el artículo";
                TempData["AlertStyle"] = AlertConstants.SUCCESS;

                return RedirectToAction("List");
            }

            return View();
        }

        public IActionResult Delete(int id)
        {
            TempData["AlertMessage"] = "Se ha eliminado el artículo '" + articleService.GetArticle(id).Name + "'";
            TempData["AlertStyle"] = AlertConstants.SUCCESS;

            articleService.DeleteArticle(id);

            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            ViewBag.Message = "Lista de artículos existentes";

            return View(articleService.GetArticles());
        }
    }
}

crud_mvc_aspnet_core/Controllers/CategoryController.cs
using crud_mvc_aspnet_core.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace crud_mvc_aspnet_core.Controllers
{
    public class CategoryController : BaseController
    {
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Message = "Ingrese los datos de la categoría";

            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                categoryService.CreateCategory(category);

                TempData["AlertMessage"] = "Se ha agregado la categoría.";
                TempData["AlertStyle"] = AlertConstants.SUCCESS;

                return RedirectToAction("List");
            }

            return View();
        }

        public IActionResult Delete(int id)
        {
            TempData["AlertMessage"] = "Se ha eliminado la categoría '" + categoryService.GetCategory(id).Name + "'";
            TempData["AlertStyle"] = AlertConstants.SUCCESS;

            categoryService.DeleteCategory(id);

            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            ViewBag.Message = "Lista de categorias existentes.";
            ViewBag.TooltipText = "No se pueden borrar categorías con artículos relacionados.";

            return View(categoryService.GetCategories());
        }
    }
}

crud_mvc_aspnet_core/Controllers/ReportController.cs
using crud_mvc_aspnet_core.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace crud_mvc_aspnet_core.Controllers
{
    public class ReportController : BaseController
    {
        public IActionResult Reports()
        {
            ViewBag.ChartTypes = new List<ChartInfo>()
            {
                new ChartInfo() { Name = "Pastel", Value = "pie" },
                new ChartInfo() { Name = "Barras", Value = "bar" }
            };

            ViewBag.Title = "Reportes";
            ViewBag.Message = "Lista de reportes";

            return View();
        }

        [HttpPost]
        public JsonResult GetDataCategories()
        {
            List<object> dataCategories = categoryService.
                GetCategories().
                Select(c => new
                {
                    name = c.Name,
                    quantity = c.Articles.Count
                }).
                Cast<object>().
                ToList();

            return Json(dataCategories);
        }
    }
}

crud_mvc_aspnet_core/Views/Shared/_AlertNotify.cshtml
@if (TempData["AlertMessage"] != null)
{
    <div class="@TempData["AlertStyle"]" role="alert">
        <p>@TempData["AlertMessage"]</p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

crud_mvc_aspnet_core/Views/Shared/_ButtonDarkMode.cshtml
@{
    bool switchIsActive = (bool)ViewBag.SwitchIsActive;
}

<li class="nav-item ml-auto" id="switch">
    <a class="btn px-2 pb-2"><i class="fa fa-sun-o fa-lg"></i></a>
    <div id="switch-2" class="custom-control custom-switch">
        <input type="checkbox" class="custom-control-input" id="btn-switch-theme" @(switchIsActive ? "checked" : "") />
        <label class="custom-control-label" for="btn-switch-theme"></label>
    </div>
    <a class="btn px-0 pb-2"><i class="fa fa-moon-o fa-lg"></i></a>
</li>

<script type="text/javascript">
    // This seccion configure the paths at the css files used in button change theme
    document.addEventListener('DOMContentLoaded', function () {
        sheetThemeLight = "@crud_mvc_aspnet_core.Controllers.ApplicationConstants.FILE_THEME_LIGHT";
        sheetThemeDark = "@crud_mvc_aspnet_core.Controllers.ApplicationConstants.FILE_THEME_DARK";
    });
</script>

crud_mvc_aspnet_core/Views/Shared/_DisplayCategoryList.cshtml
@model crud_mvc_aspnet_core.Models.Article

@{
    <select class="form-control form-control-sm" asp-for="CategoryId">
        @foreach (Category c in ViewBag.Categories)
        {
            if (Model != null && c.Id == Model.CategoryId)
            {
                <option value="@c.Id" selected>@c.Name</option>
            }
            else
            {
                <option value="@c.Id">@c.Name</option>
            }
        }
    </select>
}

crud_mvc_aspnet_core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.AppTitle</title>
    <link rel="stylesheet" href="@ViewBag.ThemeOn" id="bootstrap-theme" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-default bg-default border-bottom mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@ViewBag.AppName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Artículos</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Article" asp-action="Create">Agregar</a>
                                <div role="separator" class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Article" asp-action="List">Ver lista</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">Categorías</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Category" asp-action="Create">Agregar</a>
                                <div role="separator" class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Category" asp-action="List">Ver lista</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Report" asp-action="Reports">Reportes</a>
                        </li>
                        <partial name="_ButtonDarkMode" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderSection("ChartJs_Css", required: false)
            @RenderSection("DatatablesButtons_Css", required: false)
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - @ViewBag.AppName @ViewBag.AppVersion
        </div>
    </footer>

    <!-- jquery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/button-dark-mode.js"></script>
    @RenderSection("Scripts", required: false)

    <!-- chartjs -->
    @RenderSection("ChartJs_Js", required: false)

    <!-- jquery-datatables configuration -->
    <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/datatables-buttons/css/datatables-custom.css" />
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    @RenderSection("DatatablesButtons_Articles_Js", required: false)
    @RenderSection("DatatablesButtons_Categories_Js", required: false)
    @RenderSection("DatatablesButtons_Js", required: false)

    <!-- bootstrap -->
    @RenderSection("BootstrapCustom_Js", required: false)
</body>
</html>

crud_mvc_aspnet_core/Views/Shared/_PopupNotify.cshtml
@model string

<div class="modal fade" id="popupNotify" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content bg-success">
            <div class="modal-body text-white">
                @Model
            </div>
        </div>
    </div>
</div>